[package]
name = "fbkl-migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "fbkl_migration"
path = "src/lib.rs"

[dependencies]
async-sea-orm-session = { git = "https://github.com/dcchut/async-sea-orm-session", rev = "aa800f0b417c3a711ba4aac2453ff8040bd7e506" }
async-std = { version = "^1", features = ["attributes", "tokio1"] }

[dependencies.sea-orm-migration]
version = "^0.9.0"
features = [
  "runtime-tokio-rustls",
  "sqlx-postgres"
]
