packages:
  - webapp-logged-in
  - webapp-public
allowBuilds:
  '@evilmartians/lefthook': true
minimumReleaseAgeExclude:
  - '@tanstack/router-generator@1.167.21'
  - '@tanstack/router-plugin@1.168.22'
onlyBuiltDependencies:
  - '@evilmartians/lefthook'
  - esbuild
  - sharp
