[package]
name = "fbkl-entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = {git = "https://github.com/kaibyao/async-graphql"}
sea-orm = { version = "^0", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros" ] }
serde = "1.0.144"
