import { ContractKind } from '@/generated/graphql';

// `ContractKind` is generated by the client-preset as a string-literal union
// (not a runtime enum), so the GraphQL enum values are used directly here.
/** Contracts that are active on a team and take up a team's salary/cap space. */
const ACTIVE_CONTRACT_KINDS = new Set<ContractKind>([
  'ROOKIE',
  'ROOKIE_EXTENSION',
  'VETERAN',
]);

export const isContractActiveOnTeam = (contractKind: ContractKind) =>
  ACTIVE_CONTRACT_KINDS.has(contractKind);
