[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-identity = "0.5.2"
actix-session = {version = "0.7.1", features = ["cookie-session"]}
actix-web = "4.1.0"
axum = {version = "0.6.0-rc.2"}
axum-macros = "0.2.3"
color-eyre = "0.6.2"
dotenv = "0.15.0"
fbkl-auth = { path = "../auth" }
fbkl-db = { path = "../db" }
serde = { version = "1.0.143", features = ["derive"] }
tokio = {version = "1.20.1", features = ["full"]}
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter", "fmt"] }

[target.aarch64-apple-darwin]
rustflags = '-L /opt/homebrew/opt/libpq/lib -L /opt/homebrew/lib'
