[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1.0"
color-eyre = "0.6.2"
diesel = { version = "1.4.8", features = ["postgres"] }
dotenv = "0.15.0"
tokio = {version = "1.20.1", features = ["full"]}
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter", "fmt"] }
