[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1.0"
color-eyre = "0.6.2"
tokio = {version = "1.20.1", features = ["full"]}
