[package]
name = "fbkl-graphql-generation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = "7.0.7"
fbkl-server = { path = "../server"}
