//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "auction")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub start_timestamp: DateTimeWithTimeZone,
    pub soft_end_timestamp: DateTimeWithTimeZone,
    pub fixed_end_timestamp: DateTimeWithTimeZone,
    pub contract_id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contract::Entity",
        from = "Column::ContractId",
        to = "super::contract::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Contract,
    #[sea_orm(has_many = "super::auction_bid::Entity")]
    AuctionBid,
}

impl Related<super::contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contract.def()
    }
}

impl Related<super::auction_bid::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuctionBid.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
