//! `SeaORM` Entity. Generated by sea-orm-codegen 0.9.2

use std::fmt::Debug;

use async_graphql::Enum;
use color_eyre::{Result, eyre::eyre};
use sea_orm::{ConnectionTrait, QueryOrder, entity::prelude::*};
use serde::{Deserialize, Serialize};
use tracing::instrument;

use crate::{auction_bid, contract};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "auction")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub kind: AuctionKind,
    pub status: AuctionStatus,
    pub minimum_bid_amount: i16,
    pub start_timestamp: DateTimeWithTimeZone,
    /// When the auction stops taking bids: `min(last_bid + quiet_window, all_bid_deadline)` clamped to the hard deadline (rules §6.4.4 / §8.3.1-.2). Mutable — rewritten on each bid, each veteran tier slide, and by the crunch-window sweep.
    pub close_at_timestamp: DateTimeWithTimeZone,
    /// In-season FA only: the week's Sunday 8pm CT cutoff, rolled +30min per §8.3.2. NULL for the preseason auctions, which the crunch window bounds instead.
    pub all_bid_deadline_timestamp: Option<DateTimeWithTimeZone>,
    pub contract_id: i64,
    /// The team that held the player before the auction (RFA/UFA only, rules §6.2.2.3 / §15.3.1). NULL otherwise. That team may not bid.
    pub original_owner_team_id: Option<i64>,
    /// The auction-completed transaction, set once a winning bid is signed (1:1). NULL while the auction is still open.
    pub transaction_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl Model {
    #[instrument]
    pub async fn get_bids<C>(&self, db: &C) -> Result<Vec<auction_bid::Model>>
    where
        C: ConnectionTrait + Debug,
    {
        let related_bids = self
            .find_related(auction_bid::Entity)
            .order_by_asc(auction_bid::Column::CreatedAt)
            .all(db)
            .await?;
        Ok(related_bids)
    }

    pub async fn get_latest_bid<C>(&self, db: &C) -> Result<Option<auction_bid::Model>>
    where
        C: ConnectionTrait + Debug,
    {
        let maybe_latest_bid = self
            .find_related(auction_bid::Entity)
            .order_by_desc(auction_bid::Column::CreatedAt)
            .one(db)
            .await?;
        Ok(maybe_latest_bid)
    }

    #[instrument]
    pub async fn get_contract<C>(&self, db: &C) -> Result<contract::Model>
    where
        C: ConnectionTrait + Debug,
    {
        let related_contract = self
            .find_related(contract::Entity)
            .one(db)
            .await?
            .ok_or_else(|| eyre!("Could not find contract related to auction id: {}", self.id))?;
        Ok(related_contract)
    }
}

/// Represents the different types of auctions on which owners can bid & win player contracts.
#[derive(
    Debug,
    Default,
    Clone,
    Copy,
    Eq,
    PartialEq,
    Enum,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum AuctionKind {
    /// Represents a free agent auction that happens throughout the league season.
    #[default]
    #[sea_orm(string_value = "FreeAgent")]
    InSeasonFreeAgent,
    /// Represents an auction generated as part of the veteran auction during the league preseason.
    #[sea_orm(string_value = "PreseasonVeteranAuction")]
    PreseasonVeteranAuction,
    // /// Represents a free agent auction that happens during the league preseason. This is either during the open nomination period that immediately follows the veteran auction, or the week 1 free agent period.
    // #[sea_orm(string_value = "2")]
    // PreseasonFreeAgent,
}

impl AuctionKind {
    /// Whether the auction runs in the preseason, which decides both its clocks (the crunch window
    /// bounds it, not an all-bid deadline — rules §6.4.4) and whether bids are cap- and
    /// roster-gated (§6.4.1; §8.3.5 exempts in-season free agency alone).
    ///
    /// `PreseasonFreeAgent` joins this arm when that mode lands (spec 01).
    #[must_use]
    pub const fn is_preseason(self) -> bool {
        matches!(self, Self::PreseasonVeteranAuction)
    }
}

/// Lifecycle of an auction. Replaces the old "open if now < `close_at`" inference.
#[derive(
    Debug,
    Default,
    Clone,
    Copy,
    Eq,
    PartialEq,
    Enum,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum AuctionStatus {
    /// Scheduled, not yet open for bids.
    #[sea_orm(string_value = "Pending")]
    Pending,
    /// Taking bids.
    #[default]
    #[sea_orm(string_value = "Open")]
    Open,
    /// Timer elapsed, awaiting `end_*_auction`. RFA auctions also park here for the spec 03 raise/match flow.
    #[sea_orm(string_value = "Closed")]
    Closed,
    /// Winning bid signed to a team.
    #[sea_orm(string_value = "Completed")]
    Completed,
    /// Closed with no bids; the player went back to the free agent pool.
    #[sea_orm(string_value = "Expired")]
    Expired,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contract::Entity",
        from = "Column::ContractId",
        to = "super::contract::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Contract,
    #[sea_orm(has_many = "super::auction_bid::Entity")]
    AuctionBid,
    #[sea_orm(
        belongs_to = "super::transaction::Entity",
        from = "Column::TransactionId",
        to = "super::transaction::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Transaction,
}

impl Related<super::contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contract.def()
    }
}

impl Related<super::auction_bid::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuctionBid.def()
    }
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
