//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use std::fmt::Debug;

use async_graphql::Enum;
use color_eyre::{eyre::eyre, Result};
use sea_orm::{entity::prelude::*, ConnectionTrait, QueryOrder, TransactionTrait};
use serde::{Deserialize, Serialize};
use tracing::instrument;

use crate::{auction_bid, contract};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "auction")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub auction_type: AuctionType,
    pub minimum_bid_amount: i16,
    pub start_timestamp: DateTimeWithTimeZone,
    pub soft_end_timestamp: DateTimeWithTimeZone,
    pub fixed_end_timestamp: DateTimeWithTimeZone,
    pub contract_id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl Model {
    #[instrument]
    pub async fn get_bids<C>(&self, db: &C) -> Result<Vec<auction_bid::Model>>
    where
        C: ConnectionTrait + TransactionTrait + Debug,
    {
        let related_bids = self
            .find_related(auction_bid::Entity)
            .order_by_asc(auction_bid::Column::CreatedAt)
            .all(db)
            .await?;
        Ok(related_bids)
    }

    pub async fn get_latest_bid<C>(&self, db: &C) -> Result<Option<auction_bid::Model>>
    where
        C: ConnectionTrait + TransactionTrait + Debug,
    {
        let maybe_latest_bid = self
            .find_related(auction_bid::Entity)
            .order_by_desc(auction_bid::Column::CreatedAt)
            .one(db)
            .await?;
        Ok(maybe_latest_bid)
    }

    #[instrument]
    pub async fn get_contract<C>(&self, db: &C) -> Result<contract::Model>
    where
        C: ConnectionTrait + TransactionTrait + Debug,
    {
        let related_contract = self
            .find_related(contract::Entity)
            .one(db)
            .await?
            .ok_or_else(|| eyre!("Could not find contract related to auction id: {}", self.id))?;
        Ok(related_contract)
    }
}

/// Represents the different types of auctions on which owners can bid & win player contracts.
#[derive(
    Debug,
    Default,
    Clone,
    Copy,
    Enum,
    Eq,
    PartialEq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
)]
#[sea_orm(rs_type = "i16", db_type = "Integer")]
pub enum AuctionType {
    /// Represents a free agent auction that happens throughout the league season.
    #[default]
    #[sea_orm(num_value = 0)]
    InSeasonFreeAgent,
    /// Represents an auction generated as part of the veteran auction during the league preseason.
    #[sea_orm(num_value = 1)]
    PreseasonVeteranAuction,
    /// Represents a free agent auction that happens during the league preseason. This is either during the open nomination period that immediately follows the veteran auction, or the week 1 free agent period.
    #[sea_orm(num_value = 2)]
    PreseasonFreeAgent,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contract::Entity",
        from = "Column::ContractId",
        to = "super::contract::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Contract,
    #[sea_orm(has_many = "super::auction_bid::Entity")]
    AuctionBid,
    #[sea_orm(has_one = "super::transaction::Entity")]
    Transaction,
}

impl Related<super::contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contract.def()
    }
}

impl Related<super::auction_bid::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuctionBid.def()
    }
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
