//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::team_user;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub email: String,
    pub hashed_password: String,
    pub app_admin_status: UserAppAdminStatus,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(
    Debug, Clone, Default, Eq, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(None)")]
pub enum UserAppAdminStatus {
    #[default]
    #[sea_orm(string_value = "User")]
    User,
    #[sea_orm(string_value = "Admin")]
    Admin,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::user_registration::Entity")]
    UserRegistration,
    #[sea_orm(has_many = "super::team_user::Entity")]
    TeamUser,
}

impl Related<super::user_registration::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRegistration.def()
    }
}

impl Related<super::team_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamUser.def()
    }
}

impl Related<super::team::Entity> for Entity {
    // The final relation is User -> TeamUser -> Team
    fn to() -> RelationDef {
        team_user::Relation::Team.def()
    }

    fn via() -> Option<RelationDef> {
        // The original relation is TeamUser -> User,
        // after `rev` it becomes User -> TeamUser
        Some(team_user::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
