//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2

use async_graphql::Enum;
use color_eyre::{Result, eyre::eyre};
use sea_orm::{ActiveValue, ConnectionTrait, entity::prelude::*};
use serde::{Deserialize, Serialize};

use crate::deadline;

use super::{
    auction_transaction::new_auction_transaction,
    keeper_deadline_transaction::new_keeper_deadline_transaction,
    rookie_draft_selection_transaction::new_rookie_draft_selection_transaction,
    trade_transaction::new_trade_transaction,
};

/// A Transaction is any action taken by a user or the system that can change the state of a league or its teams.
///
/// Note that we are only recording final actions here; Intermediary actions (auction bids, trade actions) that by themselves do not change a team, contract, or the league are not recorded as a transaction.
/// Based on recorded transactions only, it should be possible to re-create the state of a league, even if intermediary data (bids, comments, trade actions that aren't the final trade state) is lost.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transaction")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub end_of_season_year: i16,
    /// Represents the different types of transactions that occur in a league.
    pub kind: TransactionKind,
    pub league_id: i64,
    /// Represents the deadline to which this transaction is tied. The reason this is necessary is because transactions may "happen" immediately, but they aren't executed until the date & time of their associated deadline.
    pub deadline_id: i64,
    /// The contract acted on by a contract-kind transaction (drop / IR / RDI / rookie activation). Set only for those kinds; the specific role is recoverable from `kind`. Trade, auction, and rookie-draft-selection transactions carry no FK here — the child row owns a `transaction_id` FK back to this row.
    pub contract_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl Model {
    /// Get the transaction's related deadline model.
    pub async fn get_deadline<C>(&self, db: &C) -> Result<deadline::Model>
    where
        C: ConnectionTrait,
    {
        self.find_related(deadline::Entity)
            .one(db)
            .await?
            .ok_or_else(|| {
                eyre!(
                    "Could not find deadline associated with transaction ({})",
                    self.id
                )
            })
    }

    /// Creates a new Auction transaction. Also note that this only creates the model, and does not persist the transaction to the database. The auction's `transaction_id` FK is set after this row is inserted (see `insert_auction_transaction`).
    pub fn new_auction_transaction(deadline_model: &deadline::Model) -> ActiveModel {
        new_auction_transaction(deadline_model)
    }

    /// Creates a new Keeper Deadline transaction (note that there should only be one per league per year). Also note that this only creates the model, and does not persist the transaction to the database.
    pub fn new_keeper_deadline_transaction(keeper_deadline_model: &deadline::Model) -> ActiveModel {
        new_keeper_deadline_transaction(keeper_deadline_model)
    }

    pub fn new_preseason_start_transaction(
        preseason_start_deadline_model: &deadline::Model,
    ) -> ActiveModel {
        ActiveModel {
            end_of_season_year: ActiveValue::Set(preseason_start_deadline_model.end_of_season_year),
            kind: ActiveValue::Set(TransactionKind::PreseasonStart),
            league_id: ActiveValue::Set(preseason_start_deadline_model.league_id),
            deadline_id: ActiveValue::Set(preseason_start_deadline_model.id),
            ..Default::default()
        }
    }

    pub fn new_rookie_draft_selection_transaction(deadline_model: &deadline::Model) -> ActiveModel {
        new_rookie_draft_selection_transaction(deadline_model)
    }

    pub fn new_trade_transaction(deadline_model: &deadline::Model) -> ActiveModel {
        new_trade_transaction(deadline_model)
    }
}

/// Represents the different types of transactions that occur in a league.
#[derive(
    Debug, Clone, Copy, Eq, PartialEq, Enum, EnumIter, DeriveActiveEnum, Serialize, Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum TransactionKind {
    /// The transaction is a trade between two teams.
    #[sea_orm(string_value = "Trade")]
    Trade,
    /// The transaction is the result of a team winning a player auction.
    #[sea_orm(string_value = "AuctionDone")]
    AuctionDone,
    /// Pre-season start.
    #[sea_orm(string_value = "PreseasonStart")]
    PreseasonStart,
    /// Pre-season keepers set.
    #[sea_orm(string_value = "PreseasonKeeper")]
    PreseasonKeeper,
    /// A rookie player was selected during the rookie draft.
    #[sea_orm(string_value = "RookieDraftSelection")]
    RookieDraftSelection,
    /// A team has manually dropped a player contract.
    #[sea_orm(string_value = "TeamUpdateDropContract")]
    TeamUpdateDropContract,
    /// A team has moved a player contract to IR.
    #[sea_orm(string_value = "TeamUpdateToIr")]
    TeamUpdateToIr,
    /// A team has moved a player contract from IR.
    #[sea_orm(string_value = "TeamUpdateFromIr")]
    TeamUpdateFromIr,
    /// A team has moved an RD player contract to RDI.
    #[sea_orm(string_value = "TeamUpdateToRdi")]
    TeamUpdateToRdi,
    /// A team has moved an RDI player contract back to RD.
    #[sea_orm(string_value = "TeamUpdateFromRdi")]
    TeamUpdateFromRdi,
    /// A team has activated a rookie contract, converting them to a rookie extension.
    #[sea_orm(string_value = "RookieContractActivation")]
    RookieContractActivation,
    /// A team has made a configuration change (ownership/name change).
    #[sea_orm(string_value = "TeamUpdateConfigChange")]
    TeamUpdateConfigChange,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "crate::auction::Entity")]
    Auction,
    #[sea_orm(
        belongs_to = "crate::deadline::Entity",
        from = "Column::DeadlineId",
        to = "crate::deadline::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Deadline,
    #[sea_orm(
        belongs_to = "crate::contract::Entity",
        from = "Column::ContractId",
        to = "crate::contract::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Contract,
    #[sea_orm(
        belongs_to = "crate::league::Entity",
        from = "Column::LeagueId",
        to = "crate::league::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    League,
    #[sea_orm(has_one = "crate::rookie_draft_selection::Entity")]
    RookieDraftSelection,
    #[sea_orm(has_many = "crate::team_update::Entity")]
    TeamUpdate,
    #[sea_orm(has_one = "crate::trade::Entity")]
    Trade,
}

impl Related<crate::auction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Auction.def()
    }
}

impl Related<crate::contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contract.def()
    }
}

impl Related<crate::deadline::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deadline.def()
    }
}

impl Related<crate::league::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::League.def()
    }
}

impl Related<crate::rookie_draft_selection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RookieDraftSelection.def()
    }
}

impl Related<crate::team_update::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamUpdate.def()
    }
}

impl Related<crate::trade::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trade.def()
    }
}

// No before_save validator: migration m20260722_000001 collapsed the 7 nullable FK columns, so the old illegal states are no longer representable.
impl ActiveModelBehavior for ActiveModel {}
